### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by brandonkal** [gitpod-io/dazzle#4]
This looks like it is something that will solve some pain points with building complex container images.

I have two suggestions that may have already been considered so feel free to ignore them:

- This would make more sense implemented as a [Docker frontend](https://matt-rickard.com/building-a-new-dockerfile-frontend/) rather than creating another CLI that then calls docker. Given that this project only adds a small amount of additional syntax, I imagine interacting with Docker's LLB as a more efficient approach. I just discovered this possibility myself.
- [`RUN --mount=type=cache`](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/experimental.md#run---mounttypecache) support. It is not clear if this is possible when used in combination with dazzle.

I am curious if you have discovered any other similar tools / alternative OCI build tools in your research. [Ansible Bender](https://github.com/ansible-community/ansible-bender) looks more composable than templating out a large Dockerfile, especially given that Ansible roles already exist for every component. However, that project does not yet have a means to specify when a layer doesn't depend on a previous layer.

**Comment by 32leaves** [comment]
> This looks like it is something that will solve some pain points with building complex container images.
> 
> I have two suggestions that may have already been considered so feel free to ignore them:
> 
> * This would make more sense implemented as a [Docker frontend](https://matt-rickard.com/building-a-new-dockerfile-frontend/) rather than creating another CLI that then calls docker. Given that this project only adds a small amount of additional syntax, I imagine interacting with Docker's LLB as a more efficient approach. I just discovered this possibility myself.

I did consider buildkits LLB functionality at the time. dazzle could use that functionality to build the individual chunks/layers instead of manually splitting out Docker files. While this does feel cleaner than the current way (and would be faster due to buildkit's parallel builds), it's also more complex and harder to debug. At the moment, as user of dazzle you can get a really good understanding of what happens just by looking at the Dockerfiles dazzle generates during the build.

> * [`RUN --mount=type=cache`](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/experimental.md#run---mounttypecache) support. It is not clear if this is possible when used in combination with dazzle.

That is a good point which I hadn't thought about or experimented with. 

> I am curious if you have discovered any other similar tools / alternative OCI build tools in your research. [Ansible Bender](https://github.com/ansible-community/ansible-bender) looks more composable than templating out a large Dockerfile, especially given that Ansible roles already exist for every component. However, that project does not yet have a means to specify when a layer doesn't depend on a previous layer.

I hadn't come across a tool that specifically builds independent layers. [Buildpacks](https://buildpacks.io/) do something similar but specifically for building/deploying code rather than generic images.

W.r.t. to templating out of a large Dockerfile: initially I just tried to "recombine" individual images by factoring out a shared base image. This way one could build each layer from their own Dockerfile. This did prove quite cumbersome and difficult to handle though (e.g. making sure that all images were built from the exact same version of `alpine:latest`).
